### ISSUE TITLE
Profile for HPLib/HPCups

### ISSUE THREAD

**Issue by NovaViper** [xyproto/ufw-extras#7]
Hi! I'm wondering if you can add a profile that unblocks the HP printer drivers/library that comes with Manjaro. Whenever I go and try to scan for devices on my network, it gets blocked by ufw. This is the program: https://developers.hp.com/hp-linux-imaging-and-printing/

**Comment by xyproto** [comment]
Hi, sure, but do you happen to know which port numbers are involved? Could it be port 631 (the port used by cups)?

**Comment by xyproto** [comment]
After some searching it appears it could be:

Port 161,162 and 9100 (all TCP ports, I assume).

**Comment by xyproto** [comment]
I added one file for HPLIP and one for CUPS and created a new release.

Please test!

**Comment by NovaViper** [comment]
Cool, I'm actually trying to figure out how to import the profiles into ufw/gufw.. How do I do that?

**Comment by NovaViper** [comment]
When I try to import, Gufw keeps saying filename has wrong permissions (not 600)

**Comment by xyproto** [comment]
I haven't used Gufw, but if you run `chmod 600` on the file, it should change the permissions

 Alternatively, in some file management applications you can right click the file, find the right settings view and change the permissions to read only (not write) and only for the current user, to achieve the same as `chmod 600`.

**Comment by NovaViper** [comment]
Oof.. apparently when I go and import, it doesn't even appear in gufw <_> Is there any other way of importing the profile into UFW in general?

**Comment by xyproto** [comment]
Yes, just `sudo ufw allow hplip`.

The ufw files needs to be copied to the right location on your system first, though. Typically `/etc/ufw/applications.d/`.

**Comment by NovaViper** [comment]
Sorry for the late reply! I've been busy with school and had to format both my computers, so I didn't get the chance to test it.

**Comment by NovaViper** [comment]
Alrighty, finally got to test it but noticed that it doesn't work. HPLIP still seems to be blocked by the firewall :(

**Comment by xyproto** [comment]
Aw. Thanks for testing, though! I updated the hplip file to also open up UDP port 5353, perhaps this helps?

**Comment by NovaViper** [comment]
Just tested it again, still being blocked :(

**Comment by NovaViper** [comment]
From what I can see, it seems to be generating ports randomly

**Comment by xyproto** [comment]
Ports in one direction may be randomly chosen (and not normally blocked by a firewall), while ports in the other direction may depend on the ports being open with the currently running firewall.

Does it work if you turn off ufw altogether? If it then still does not work, then it's not an ufw configuration issue.

**Comment by NovaViper** [comment]
Yeah, it works when I disable UFW completely

**Comment by xyproto** [comment]
I added port 137 as well, to the file that is in the latest `master`. Perhaps it works now?

If not, could it be that you have the same issue as in this bug report? https://answers.launchpad.net/hplip/+question/664494

**Comment by NovaViper** [comment]
Oddly enough, it's still not working :( I went and followed the steps that were listed in the launchpad link, nothing

**Comment by xyproto** [comment]
I'm bummed out. If you ever find the right TCP and UDP ports, please let me know, and I'll update the file. :)

**Comment by NovaViper** [comment]
Hmm.. maybe put in TCP and UDP types for reach port number?

**Comment by xyproto** [comment]
Those ports should be open.

Have you tried updating the hplip driver?

https://askubuntu.com/a/1165788/19017

**Comment by xyproto** [comment]
Please re-open if this is still an issue.

**Comment by NovaViper** [comment]
Unfortunately the issue is still present, even with the latest version of hplip. I haven't been able to figure out a solution other than disabling ufw permanently
